---
- name: configuring web server
  hosts: web
  become: yes
  tasks:
    - name: copy index.html
      ansible.builtin.copy:
        src: /home/karthick/workspace/webpage/index.html
        dest: /var/www/html/index.html

    - name: copy docker file
      ansible.builtin.copy:
        src: /home/karthick/workspace/webpage/Dockerfile
        dest: /root/project/Dockerfile
    - name: Building Docker Image
      docker_image:
        name: amazonlinux:latest
        source: build
        build:
          path: /root/project/
    - name: Creating the container
      docker_container:
        name: amazon
        image: amazonlinux:latest
        state: started
        ports:
          - "80:80"
    - name: copy index.html
      community.docker.docker_container_copy_into:
        container: amazon
        path: /var/www/html/index.html
        container_path: /var/www/html/index.html
   
         
